@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TAilorParser" as TAilorParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedContent" as VersionedContent MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> TAilorParser : parseCommand(undo)
activate TAilorParser

create UndoCommand
TAilorParser -> UndoCommand
activate UndoCommand

UndoCommand --> TAilorParser
deactivate UndoCommand

TAilorParser --> LogicManager : u
deactivate TAilorParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoContent()
activate Model

Model -> VersionedContent : undo()
activate VersionedContent

VersionedContent -> VersionedContent :resetData(ReadOnlyContent)
VersionedContent --> Model :
deactivate VersionedContent

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
